setwd("~/Monica/DataScience/ExploratoryDataAnalysis/exdata%2Fdata%2Fhousehold_power_consumption (1)")
data <- read.csv("household_power_consumption.txt", sep = ";", na.strings = "?")
colnames(data) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
newdata <- subset(data, subset = (data$Date >= "2007-02-01" & Date <= "2007-02-02"))
newdata$dt <- as.POSIXct(paste(newdata$Date, newdata$Time))
plot(newdata$Sub_metering_1 ~ newdata$dt, type = "l", col = "black", xlab = " ", ylab = "Energy sub metering", main = "")
lines(newdata$dt, newdata$Sub_metering_2, type = "l", col = "red" )
lines(newdata$dt, newdata$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = c(1,1,1))
